import Tomabechi.Theorem27.Abstract
import Tomabechi.Theorem27.Actuator

/-! 定理27.6以降の残差減衰と行為帰結への接続。-/

namespace Tomabechi.Theorem27

open _root_.Tomabechi.Theorem24_26

/-- Residual descent rate along a specified closed-loop trajectory, with the
paper's convention `Des = -D⁺ W`. -/
noncomputable def residualDescentRateAlong
    (W : ℝ → X → ℝ) (x : ℝ → X) (t : ℝ) : ℝ :=
  -Actuator.upperRightDiniDerivative (fun s => W s (x s)) t

/-- Pointwise equation (27.6) for a time-varying closed zero-residual target.
The lower distance comparison and strict Dini decay are precisely the
conditions inherited from 26-A; operational ignorance is `x t ∉ N t`. -/
theorem theorem27_residual_descent_at_time
    {X : Type*} [PseudoMetricSpace X]
    (N : ℝ → Set X) (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (W : ℝ → X → ℝ) (x : ℝ → X)
    (c₁ decayRate : ℝ) (hc₁ : 0 < c₁) (hdecayRate : 0 < decayRate)
    (hWlower : ∀ t,
      c₁ * (Metric.infDist (x t) (N t)) ^ 2 ≤ W t (x t))
    (hDiniDecay : ∀ t,
      decayRate * W t (x t) ≤
        -Actuator.upperRightDiniDerivative (fun s => W s (x s)) t)
    (t : ℝ) (htopIgnorance : x t ∉ N t) :
    decayRate * c₁ * (Metric.infDist (x t) (N t)) ^ 2 ≤
        residualDescentRateAlong W x t ∧
      0 < residualDescentRateAlong W x t := by
  exact residual_descent_of_outside_closed_target (N t) (hNclosed t)
    (hNnonempty t) (W t) (x t) c₁ decayRate hc₁ hdecayRate
    (residualDescentRateAlong W x t) (hWlower t) (hDiniDecay t)
    htopIgnorance

/-- Integrated highest-level conclusion (27.6): with the common optimal
feedback and the PZS definition from theorem 26, operational ignorance from
an alive initial pair implies the quantitative residual-descent bound.

The data are indexed by the initial pair `(x t,t)` along the specified
trajectory. The future-time measures, feedback admissibility and trajectory
running values, global optimality/attainment, and conditions 26-A are all
explicit hypotheses; the conclusion is pointwise, as in (27.6). -/
theorem theorem27_feedback_ignorance_implies_residual_descent
    {State Feedback : Type*} [PseudoMetricSpace State] [MeasurableSpace ℝ]
    (μ : ℝ → MeasureTheory.Measure ℝ) (ρ : ℝ)
    (runningValue : Feedback → State → ℝ → ℝ → ℝ)
    (admissible : Feedback → State → ℝ → Prop)
    (π₀ : Feedback) (alive : ℝ → Set State)
    (optimalValue : State → ℝ → ℝ)
    (x : ℝ → State) (W : ℝ → State → ℝ)
    (c₁ decayRate : ℝ) (hc₁ : 0 < c₁) (hdecayRate : 0 < decayRate)
    (hnonneg : ∀ t π, admissible π (x t) t →
      ∀ᵐ s ∂(μ t), 0 ≤ runningValue π (x t) t s)
    (hint : ∀ t π, admissible π (x t) t →
      MeasureTheory.Integrable
        (fun s => theorem26DiscountWeight ρ t s * runningValue π (x t) t s)
        (μ t))
    (hπ₀ : ∀ t, admissible π₀ (x t) t)
    (hattains : ∀ t, optimalValue (x t) t =
      discountedFeedbackValue μ (theorem26DiscountWeight ρ)
        runningValue π₀ (x t) t)
    (hminimal : ∀ t π, admissible π (x t) t →
      optimalValue (x t) t ≤ discountedFeedbackValue μ
        (theorem26DiscountWeight ρ) runningValue π (x t) t)
    (halive : ∀ t, x t ∈ alive t)
    (hNclosed : ∀ t,
      IsClosed (theorem26ZeroValueTarget (alive t) optimalValue t))
    (hNnonempty : ∀ t,
      (theorem26ZeroValueTarget (alive t) optimalValue t).Nonempty)
    (hWlower : ∀ t,
      c₁ * (Metric.infDist (x t)
        (theorem26ZeroValueTarget (alive t) optimalValue t)) ^ 2 ≤ W t (x t))
    (hDiniDecay : ∀ t, decayRate * W t (x t) ≤
      -Actuator.upperRightDiniDerivative (fun s => W s (x s)) t)
    (t : ℝ)
    (hignorance : ¬FeedbackPZS admissible μ runningValue (x t) t) :
    decayRate * c₁ * (Metric.infDist (x t)
      (theorem26ZeroValueTarget (alive t) optimalValue t)) ^ 2 ≤
        residualDescentRateAlong W x t ∧
      0 < residualDescentRateAlong W x t := by
  have hpzsTarget := feedbackPZS_iff_mem_theorem26ZeroValueTarget_expDiscount
    μ ρ runningValue admissible π₀ (alive t) optimalValue (x t) t
    (hnonneg t) (hint t) (hπ₀ t) (hattains t) (hminimal t) (halive t)
  have houtside : x t ∉ theorem26ZeroValueTarget (alive t) optimalValue t := by
    intro hmem
    exact hignorance (hpzsTarget.mpr hmem)
  exact theorem27_residual_descent_at_time
    (fun s => theorem26ZeroValueTarget (alive s) optimalValue s)
    hNclosed hNnonempty W x c₁ decayRate hc₁ hdecayRate hWlower
    hDiniDecay t houtside

/-- Flow-based version of (27.6), where the running value is no longer an
independent family: it is `V` evaluated on the trajectory generated by the
same feedback, from the same initial pair. Thus PZS, `J*`, and the trajectory
whose Lyapunov residual descends share one explicit feedback dynamics model. -/
theorem theorem27_feedbackFlow_ignorance_implies_residual_descent
    {State Feedback : Type*} [PseudoMetricSpace State] [MeasurableSpace ℝ]
    (μ : ℝ → MeasureTheory.Measure ℝ) (ρ : ℝ)
    (flow : Feedback → State → ℝ → ℝ → State)
    (V : State → ℝ → ℝ)
    (admissible : Feedback → State → ℝ → Prop)
    (π₀ : Feedback) (alive : Set State)
    (optimalValue : State → ℝ → ℝ)
    (x₀ : State) (T : ℝ)
    (W : ℝ → State → ℝ)
    (c₁ decayRate : ℝ) (hc₁ : 0 < c₁) (hdecayRate : 0 < decayRate)
    (hnonneg : ∀ π, admissible π x₀ T →
      ∀ᵐ s ∂(μ T), 0 ≤ V (flow π x₀ T s) s)
    (hint : ∀ π, admissible π x₀ T →
      MeasureTheory.Integrable
        (fun s => theorem26DiscountWeight ρ T s * V (flow π x₀ T s) s) (μ T))
    (hπ₀ : admissible π₀ x₀ T)
    (hattains : optimalValue x₀ T =
      discountedFeedbackValue μ (theorem26DiscountWeight ρ)
        (fun π y S s => V (flow π y S s) s) π₀ x₀ T)
    (hminimal : ∀ π, admissible π x₀ T →
      optimalValue x₀ T ≤ discountedFeedbackValue μ (theorem26DiscountWeight ρ)
        (fun π y S s => V (flow π y S s) s) π x₀ T)
    (hInitial : flow π₀ x₀ T T = x₀)
    (hx₀ : x₀ ∈ alive)
    (N : ℝ → Set State)
    (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (hN_eq : ∀ t, N t = theorem26ZeroValueTarget alive optimalValue t)
    (hWlower : ∀ s, T ≤ s →
      c₁ * (Metric.infDist (flow π₀ x₀ T s) (N s)) ^ 2 ≤
        W s (flow π₀ x₀ T s))
    (hDiniDecay : ∀ s, T ≤ s →
      decayRate * W s (flow π₀ x₀ T s) ≤
        -Actuator.upperRightDiniDerivative
          (fun r => W r (flow π₀ x₀ T r)) s)
    (hignorance :
      ¬FeedbackPZS admissible μ
        (fun π y S s => V (flow π y S s) s) x₀ T) :
    decayRate * c₁ * (Metric.infDist x₀ (N T)) ^ 2 ≤
        residualDescentRateAlong W (flow π₀ x₀ T) T ∧
      0 < residualDescentRateAlong W (flow π₀ x₀ T) T := by
  have hpzsTarget := feedbackPZS_iff_mem_theorem26ZeroValueTarget_expDiscount
    μ ρ (fun π y S s => V (flow π y S s) s) admissible π₀ alive
    optimalValue x₀ T hnonneg hint hπ₀ hattains hminimal hx₀
  have houtside : x₀ ∉ N T := by
    intro hxN
    have hxTarget : x₀ ∈ theorem26ZeroValueTarget alive optimalValue T := by
      rw [← hN_eq T]
      exact hxN
    exact hignorance (hpzsTarget.mpr hxTarget)
  have hstartW : W T (flow π₀ x₀ T T) = W T x₀ := by rw [hInitial]
  have hstartDistance : Metric.infDist (flow π₀ x₀ T T) (N T) =
      Metric.infDist x₀ (N T) := by rw [hInitial]
  have hWlowerStart : c₁ * (Metric.infDist x₀ (N T)) ^ 2 ≤ W T x₀ := by
    rw [← hstartW, ← hstartDistance]
    exact hWlower T le_rfl
  have hDiniStart : decayRate * W T x₀ ≤
      residualDescentRateAlong W (flow π₀ x₀ T) T := by
    rw [← hstartW]
    exact hDiniDecay T le_rfl
  exact residual_descent_of_outside_closed_target (N T) (hNclosed T)
    (hNnonempty T) (W T) x₀ c₁ decayRate hc₁ hdecayRate
    (residualDescentRateAlong W (flow π₀ x₀ T) T) hWlowerStart
    hDiniStart houtside

/-- Flow-level implication (27.7). The policies are global Markov feedbacks;
their running value is `V` evaluated on their own state flow. The restart
identity ties each future segment of the specified closed-loop trajectory to
the same feedback started from its current state. From a.e. failure of PZS,
the theorem-26 optimal-value characterization and 26-A imply a.e. positive
residual, after which the 27-A chain rule and reference-loop cancellation
give positive actuator contribution and nonzero input/state action. -/
theorem theorem27_feedbackFlow_ignorance_implies_actuator_action_of_ac_ode
    {ι U : Type*} [Fintype ι]
    [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
    (μ : ℝ → MeasureTheory.Measure ℝ) (ρ : ℝ)
    (flow : (ℝ → EuclideanSpace ℝ ι → U) →
      EuclideanSpace ℝ ι → ℝ → ℝ → EuclideanSpace ℝ ι)
    (V : EuclideanSpace ℝ ι → ℝ → ℝ)
    (admissible : (ℝ → EuclideanSpace ℝ ι → U) →
      EuclideanSpace ℝ ι → ℝ → Prop)
    (π₀ : ℝ → EuclideanSpace ℝ ι → U)
    (alive : Set (EuclideanSpace ℝ ι))
    (optimalValue : EuclideanSpace ℝ ι → ℝ → ℝ)
    (x : ℝ → EuclideanSpace ℝ ι)
    (hfuture : ∀ t, ∀ᵐ s ∂(μ t), t ≤ s)
    (hflow : ∀ t s, t ≤ s → flow π₀ (x t) t s = x s)
    (hnonneg : ∀ t π, admissible π (x t) t →
      ∀ᵐ s ∂(μ t), 0 ≤ V (flow π (x t) t s) s)
    (hint : ∀ t π, admissible π (x t) t →
      MeasureTheory.Integrable
        (fun s => theorem26DiscountWeight ρ t s * V (flow π (x t) t s) s)
        (μ t))
    (hπ₀ : ∀ t, admissible π₀ (x t) t)
    (hvalue : ∀ t, optimalValue (x t) t =
      ∫ s, theorem26DiscountWeight ρ t s * V (x s) s ∂(μ t))
    (hminimal : ∀ t π, admissible π (x t) t →
      optimalValue (x t) t ≤ discountedFeedbackValue μ
        (theorem26DiscountWeight ρ)
        (fun π y T s => V (flow π y T s) s) π (x t) t)
    (halive : ∀ t, x t ∈ alive)
    (hignorance : ∀ᵐ t,
      ¬FeedbackPZS admissible μ (fun π y T s => V (flow π y T s) s)
        (x t) t)
    (N : ℝ → Set (EuclideanSpace ℝ ι))
    (hN_eq : ∀ t, N t = theorem26ZeroValueTarget alive optimalValue t)
    (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (W : ℝ × EuclideanSpace ℝ ι → ℝ)
    (dW : ℝ → (ℝ × EuclideanSpace ℝ ι →L[ℝ] ℝ))
    (gradW drift : ℝ → EuclideanSpace ℝ ι)
    (utr : ℝ → U) (actuator : ℝ → U →L[ℝ] (EuclideanSpace ℝ ι))
    (decayRate c₁ L : ℝ) (hdecayRate : 0 < decayRate)
    (hc₁ : 0 < c₁) (hL : 0 < L)
    (hWlower : ∀ᵐ t,
      c₁ * (Metric.infDist (x t) (N t)) ^ 2 ≤ W (t, x t))
    (hDiniDecay : ∀ᵐ t,
      decayRate * W (t, x t) ≤
        -Actuator.upperRightDiniDerivative (fun s => W (s, x s)) t)
    (hW : ∀ t, HasFDerivAt W (dW t) (t, x t))
    (hac : ∀ a b, AbsolutelyContinuousOnInterval x a b)
    (hODE : ∀ᵐ t,
      deriv x t = drift t + actuator t (π₀ t (x t)))
    (hstateGradient : ∀ᵐ t, ∀ z,
      dW t (0, z) = inner ℝ (gradW t) z)
    (hReference : ∀ᵐ t,
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0)
    (hgradientBound : ∀ᵐ t,
      ‖(actuator t).adjoint (gradW t)‖ ≤ L)
    (hLocallyLipschitz : LocallyLipschitz (fun s => W (s, x s))) :
    ∀ᵐ t,
      0 < -(inner ℝ (gradW t)
        (actuator t (π₀ t (x t) - utr t))) ∧
      π₀ t (x t) - utr t ≠ 0 ∧
      actuator t (π₀ t (x t) - utr t) ≠ 0 ∧
      decayRate * c₁ * (Metric.infDist (x t) (N t)) ^ 2 / L ≤
        ‖π₀ t (x t) - utr t‖ := by
  have hOutside : ∀ᵐ t, x t ∉ N t := by
    filter_upwards [hignorance] with t hnotPZS
    have hpzsTarget := feedbackPZS_iff_mem_theorem26ZeroValueTarget_expDiscount
      (μ := μ) ρ (fun π y T s => V (flow π y T s) s) admissible π₀ alive
      optimalValue (x t) t (hnonneg t) (hint t) (hπ₀ t)
      (by
        calc
          optimalValue (x t) t =
              ∫ s, theorem26DiscountWeight ρ t s * V (x s) s ∂(μ t) :=
            hvalue t
          _ = discountedFeedbackValue μ (theorem26DiscountWeight ρ)
              (fun π y T s => V (flow π y T s) s) π₀ (x t) t := by
            unfold discountedFeedbackValue
            apply MeasureTheory.integral_congr_ae
            filter_upwards [hfuture t] with s hs
            rw [hflow t s hs])
      (hminimal t) (halive t)
    have houtside : x t ∉ theorem26ZeroValueTarget alive optimalValue t := by
      intro hmem
      exact hnotPZS (hpzsTarget.mpr hmem)
    rw [hN_eq t]
    exact houtside
  have hResidualPositive : ∀ᵐ t, 0 < W (t, x t) := by
    filter_upwards [hOutside, hWlower] with t houtside hLower
    have hdist : 0 < Metric.infDist (x t) (N t) :=
      (hNclosed t).notMem_iff_infDist_pos (hNnonempty t) |>.mp houtside
    have hsq : 0 < (Metric.infDist (x t) (N t)) ^ 2 := sq_pos_of_pos hdist
    nlinarith
  have hAction := Actuator.ae_ignorance_implies_model_relative_action_of_ac_ode
    W x dW gradW drift (fun t => π₀ t (x t)) utr actuator decayRate
    hdecayRate hW hac hODE hstateGradient hReference hResidualPositive
    hLocallyLipschitz hDiniDecay
  have hControl := Actuator.ae_control_difference_distance_lower_bound_of_dini_of_ac_ode
    N hNclosed hNnonempty W x dW gradW drift (fun t => π₀ t (x t)) utr
    actuator c₁ decayRate L hc₁ hdecayRate hL hW hac hODE hstateGradient
    hReference hWlower hDiniDecay hLocallyLipschitz hgradientBound
  filter_upwards [hAction, hControl] with t hAction hControl
  exact ⟨hAction.1, hAction.2.1, hAction.2.2, hControl.1⟩

/-- The target-entry part of (27.9), with the target fixed to the theorem-26
zero-optimal-value set. The two-sided 26-A distance comparison first gives
`W=0` on `N_top`; forward invariance then gives zero Dini descent at every
later time and zero actuator contribution almost everywhere thereafter. -/
theorem theorem27_target_entry_implies_quiescence
    {E U : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup U] [InnerProductSpace ℝ U]
    (alive : Set E) (Jstar : E → ℝ → ℝ) (N : ℝ → Set E)
    (W : ℝ × E → ℝ) (hN_eq : ∀ t, N t = theorem26ZeroValueTarget alive Jstar t)
    (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (c₁ c₂ : ℝ)
    (hLower : ∀ t y, y ∈ alive →
      c₁ * (Metric.infDist y (N t)) ^ 2 ≤ W (t, y))
    (hUpper : ∀ t y, y ∈ alive →
      W (t, y) ≤ c₂ * (Metric.infDist y (N t)) ^ 2)
    (x : ℝ → E)
    (hforward : ∀ T s, T ≤ s → x T ∈ N T → x s ∈ N s)
    (dW : ℝ → (ℝ × E →L[ℝ] ℝ)) (gradW drift : ℝ → E)
    (u0 utr : ℝ → U) (actuator : ℝ → U →L[ℝ] E)
    (hW : ∀ t, HasFDerivAt W (dW t) (t, x t))
    (hmodel : ∀ᵐ t,
      HasDerivAt x (drift t + actuator t (u0 t)) t ∧
      (∀ z, dW t (0, z) = inner ℝ (gradW t) z) ∧
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0)
    (hLocallyLipschitz : LocallyLipschitz (fun s => W (s, x s)))
    (T : ℝ) (hTtarget : x T ∈ N T) :
    (∀ t, T ≤ t → residualDescentRateAlong (fun s y => W (s, y)) x t = 0) ∧
    (∀ᵐ t, T ≤ t →
      inner ℝ (gradW t) (actuator t (u0 t - utr t)) = 0) := by
  have hWzero : ∀ s y, y ∈ N s → W (s, y) = 0 := by
    intro s y hy
    exact residual_eq_zero_on_theorem26_target alive Jstar N W hN_eq
      hNclosed hNnonempty c₁ c₂ hLower hUpper s y hy
  have hdescent : ∀ t, T ≤ t →
      residualDescentRateAlong (fun s y => W (s, y)) x t = 0 := by
    intro t hTt
    exact Actuator.residualDescentRate_zero_after_target_entry N W x hforward hWzero
      T t hTt hTtarget
  have hmodelZero :
      ∀ᵐ t, T ≤ t →
        inner ℝ (gradW t) (actuator t (u0 t - utr t)) = 0 :=
    Actuator.ae_actuator_contribution_zero_after_target_entry N W x hforward hWzero
      dW gradW drift u0 utr actuator hW hmodel hLocallyLipschitz T hTtarget
  exact ⟨hdescent, hmodelZero⟩

/-- Future-domain adapter for (27.9).  The target-entry/zero-descent part is
pointwise for every later time; the model data and regularity for the actuator
conclusion are needed only almost everywhere on the future ray. -/
theorem theorem27_target_entry_implies_quiescence_on_future
    {E U : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup U] [InnerProductSpace ℝ U]
    (alive : Set E) (Jstar : E → ℝ → ℝ) (N : ℝ → Set E)
    (W : ℝ × E → ℝ) (hN_eq : ∀ t, N t = theorem26ZeroValueTarget alive Jstar t)
    (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (c₁ c₂ : ℝ)
    (hLower : ∀ t y, y ∈ alive →
      c₁ * (Metric.infDist y (N t)) ^ 2 ≤ W (t, y))
    (hUpper : ∀ t y, y ∈ alive →
      W (t, y) ≤ c₂ * (Metric.infDist y (N t)) ^ 2)
    (x : ℝ → E)
    (hforward : ∀ T s, T ≤ s → x T ∈ N T → x s ∈ N s)
    (dW : ℝ → (ℝ × E →L[ℝ] ℝ)) (gradW drift : ℝ → E)
    (u0 utr : ℝ → U) (actuator : ℝ → U →L[ℝ] E)
    (T : ℝ)
    (hW : ∀ᵐ t ∂_root_.Tomabechi.Theorem24_26.futureLebesgueMeasure T,
      HasFDerivAt W (dW t) (t, x t))
    (hmodel : ∀ᵐ t ∂_root_.Tomabechi.Theorem24_26.futureLebesgueMeasure T,
      HasDerivAt x (drift t + actuator t (u0 t)) t ∧
      (∀ z, dW t (0, z) = inner ℝ (gradW t) z) ∧
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0)
    (hLocallyLipschitz : LocallyLipschitzOn (Set.Ici T)
      (fun s => W (s, x s))) (hTtarget : x T ∈ N T) :
    (∀ t, T ≤ t → residualDescentRateAlong (fun s y => W (s, y)) x t = 0) ∧
    (∀ᵐ t ∂_root_.Tomabechi.Theorem24_26.futureLebesgueMeasure T,
      inner ℝ (gradW t) (actuator t (u0 t - utr t)) = 0) := by
  have hWzero : ∀ s y, y ∈ N s → W (s, y) = 0 := by
    intro s y hy
    exact residual_eq_zero_on_theorem26_target alive Jstar N W hN_eq
      hNclosed hNnonempty c₁ c₂ hLower hUpper s y hy
  have hdescent : ∀ t, T ≤ t →
      residualDescentRateAlong (fun s y => W (s, y)) x t = 0 := by
    intro t hTt
    exact Actuator.residualDescentRate_zero_after_target_entry N W x
      hforward hWzero T t hTt hTtarget
  have hmodelZero :=
    Actuator.ae_actuator_contribution_zero_after_target_entry_on_future
      N W x hforward hWzero dW gradW drift u0 utr actuator T hW hmodel
      hLocallyLipschitz hTtarget
  exact ⟨hdescent, hmodelZero⟩

/-- Equation (27.9) from theorem-26 PZS itself. The common Markov feedback's
flow and the running value `V` define PZS and `J*`; its optimality identifies
PZS with entry into `N_top`. Condition 26-A's two-sided distance bound gives
zero residual there, and 26-A/27-A invariance and dynamics give the two
quiescence conclusions with the paper's pointwise/a.e. quantifiers. -/
theorem theorem27_feedbackPZS_entry_implies_quiescence
    {ι U : Type*} [Fintype ι]
    [NormedAddCommGroup U] [InnerProductSpace ℝ U]
    (μ : ℝ → MeasureTheory.Measure ℝ) (ρ : ℝ)
    (flow : (ℝ → EuclideanSpace ℝ ι → U) →
      EuclideanSpace ℝ ι → ℝ → ℝ → EuclideanSpace ℝ ι)
    (V : EuclideanSpace ℝ ι → ℝ → ℝ)
    (admissible : (ℝ → EuclideanSpace ℝ ι → U) →
      EuclideanSpace ℝ ι → ℝ → Prop)
    (π₀ : ℝ → EuclideanSpace ℝ ι → U)
    (alive : Set (EuclideanSpace ℝ ι))
    (optimalValue : EuclideanSpace ℝ ι → ℝ → ℝ)
    (x : ℝ → EuclideanSpace ℝ ι) (T : ℝ)
    (hfuture : ∀ t, ∀ᵐ s ∂(μ t), t ≤ s)
    (hflow : ∀ t s, t ≤ s → flow π₀ (x t) t s = x s)
    (hnonneg : ∀ π, admissible π (x T) T →
      ∀ᵐ s ∂(μ T), 0 ≤ V (flow π (x T) T s) s)
    (hint : ∀ π, admissible π (x T) T →
      MeasureTheory.Integrable
        (fun s => theorem26DiscountWeight ρ T s * V (flow π (x T) T s) s)
        (μ T))
    (hπ₀ : admissible π₀ (x T) T)
    (hvalue : optimalValue (x T) T =
      ∫ s, theorem26DiscountWeight ρ T s * V (x s) s ∂(μ T))
    (hminimal : ∀ π, admissible π (x T) T →
      optimalValue (x T) T ≤ discountedFeedbackValue μ
        (theorem26DiscountWeight ρ)
        (fun π y S s => V (flow π y S s) s) π (x T) T)
    (hTalive : x T ∈ alive)
    (N : ℝ → Set (EuclideanSpace ℝ ι))
    (hN_eq : ∀ t, N t = theorem26ZeroValueTarget alive optimalValue t)
    (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (c₁ c₂ : ℝ)
    (W : ℝ × EuclideanSpace ℝ ι → ℝ)
    (hLower : ∀ t y, y ∈ alive →
      c₁ * (Metric.infDist y (N t)) ^ 2 ≤ W (t, y))
    (hUpper : ∀ t y, y ∈ alive →
      W (t, y) ≤ c₂ * (Metric.infDist y (N t)) ^ 2)
    (hforward : ∀ s t, s ≤ t → x s ∈ N s → x t ∈ N t)
    (dW : ℝ → (ℝ × EuclideanSpace ℝ ι →L[ℝ] ℝ))
    (gradW drift : ℝ → EuclideanSpace ℝ ι)
    (utr : ℝ → U) (actuator : ℝ → U →L[ℝ] (EuclideanSpace ℝ ι))
    (hW : ∀ t, HasFDerivAt W (dW t) (t, x t))
    (hac : ∀ a b, AbsolutelyContinuousOnInterval x a b)
    (hODE : ∀ᵐ t,
      deriv x t = drift t + actuator t (π₀ t (x t)))
    (hstateGradient : ∀ᵐ t, ∀ z,
      dW t (0, z) = inner ℝ (gradW t) z)
    (hReference : ∀ᵐ t,
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0)
    (hLocallyLipschitz :
      LocallyLipschitz (fun t => W (t, x t)))
    (hPZS : FeedbackPZS admissible μ
      (fun π y S s => V (flow π y S s) s) (x T) T) :
    (∀ t, T ≤ t →
      residualDescentRateAlong (fun s y => W (s, y)) x t = 0) ∧
    (∀ᵐ t, T ≤ t →
      inner ℝ (gradW t)
        (actuator t (π₀ t (x t) - utr t)) = 0) := by
  have hpzsTarget := feedbackPZS_iff_mem_theorem26ZeroValueTarget_expDiscount
    (μ := μ) ρ (fun π y S s => V (flow π y S s) s) admissible π₀ alive
    optimalValue (x T) T hnonneg hint hπ₀
    (by
      calc
        optimalValue (x T) T =
            ∫ s, theorem26DiscountWeight ρ T s * V (x s) s ∂(μ T) := hvalue
        _ = discountedFeedbackValue μ (theorem26DiscountWeight ρ)
            (fun π y S s => V (flow π y S s) s) π₀ (x T) T := by
          unfold discountedFeedbackValue
          apply MeasureTheory.integral_congr_ae
          filter_upwards [hfuture T] with s hs
          rw [hflow T s hs])
    hminimal hTalive
  have hTtarget : x T ∈ N T := by
    rw [hN_eq T]
    exact hpzsTarget.1 hPZS
  have hstate := Actuator.ae_hasDerivAt_pi_of_ac_and_ode x
    (fun t => drift t + actuator t (π₀ t (x t))) hac hODE
  have hmodelTuple : ∀ᵐ t,
      HasDerivAt x (drift t + actuator t (π₀ t (x t))) t ∧
      (∀ z, dW t (0, z) = inner ℝ (gradW t) z) ∧
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0 := by
    filter_upwards [hstate, hstateGradient, hReference]
      with t hstate hgradient hreference
    exact ⟨hstate, hgradient, hreference⟩
  exact theorem27_target_entry_implies_quiescence alive optimalValue N W hN_eq
    hNclosed hNnonempty c₁ c₂ hLower hUpper x hforward dW gradW drift
    (fun t => π₀ t (x t)) utr actuator hW hmodelTuple hLocallyLipschitz T hTtarget

/-- Equation (27.10) after the theorem-26 PZS characterization: once
operational ignorance has been identified pointwise with being outside
`N_top`, the existing Lyapunov and actuator equivalences give both a.e.
equivalences in the paper. The two conclusions retain their distinct
quantifiers and assumptions: (27.10)'s descent equivalence uses 26-A, while
its actuator equivalence also uses 27-A. -/
theorem theorem27_operational_ignorance_iff_descent_and_action_ae
    {E U : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup U] [InnerProductSpace ℝ U]
    (N : ℝ → Set E) (hNclosed : ∀ t, IsClosed (N t))
    (hNnonempty : ∀ t, (N t).Nonempty)
    (W : ℝ × E → ℝ) (x : ℝ → E)
    (c₁ decayRate : ℝ) (hc₁ : 0 < c₁) (hdecayRate : 0 < decayRate)
    (hWlower : ∀ᵐ t,
      c₁ * (Metric.infDist (x t) (N t)) ^ 2 ≤ W (t, x t))
    (hDiniDecay : ∀ᵐ t,
      decayRate * W (t, x t) ≤
        -Actuator.upperRightDiniDerivative (fun s => W (s, x s)) t)
    (hforward : ∀ T s, T ≤ s → x T ∈ N T → x s ∈ N s)
    (hWzero : ∀ s y, y ∈ N s → W (s, y) = 0)
    (dW : ℝ → (ℝ × E →L[ℝ] ℝ)) (gradW drift : ℝ → E)
    (u0 utr : ℝ → U) (actuator : ℝ → U →L[ℝ] E)
    (hW : ∀ t, HasFDerivAt W (dW t) (t, x t))
    (hmodel : ∀ᵐ t,
      HasDerivAt x (drift t + actuator t (u0 t)) t ∧
      (∀ z, dW t (0, z) = inner ℝ (gradW t) z) ∧
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0)
    (hLocallyLipschitz : LocallyLipschitz (fun s => W (s, x s)))
    (operationalIgnorance : ℝ → Prop)
    (hPZSOutside : ∀ t, operationalIgnorance t ↔ x t ∉ N t) :
    (∀ᵐ t, operationalIgnorance t ↔
      0 < residualDescentRateAlong (fun s y => W (s, y)) x t) ∧
    (∀ᵐ t, operationalIgnorance t ↔
      Actuator.sankhara27Contribution (gradW t) (actuator t) (u0 t - utr t)) := by
  let descent := fun t => residualDescentRateAlong (fun s y => W (s, y)) x t
  have hzeroOnTarget : ∀ᵐ t, x t ∈ N t → descent t = 0 := by
    filter_upwards with t htarget
    unfold descent residualDescentRateAlong
    rw [Actuator.upperRightDiniDerivative_zero_on_invariant_target
      N W x hforward hWzero t htarget]
    simp
  have hdescent := ae_outside_target_iff_positive_descent N hNclosed hNnonempty
    (fun t y => W (t, y)) x c₁ decayRate hc₁ hdecayRate descent
    hWlower hDiniDecay hzeroOnTarget
  have haction := Actuator.ae_outside_target_iff_positive_actuator_contribution_of_dini
    N hNclosed hNnonempty W x c₁ decayRate hc₁ hdecayRate hWlower hDiniDecay
    hforward hWzero dW gradW drift u0 utr actuator hW hmodel hLocallyLipschitz
  constructor
  · filter_upwards [hdescent] with t hdescent
    exact (hPZSOutside t).trans hdescent
  · filter_upwards [haction] with t haction
    exact (hPZSOutside t).trans haction

/-- Future-ray form of (27.10). All target and 26-A bounds are required only
on `[T,∞)`, matching theorem 26's nonnegative-time domain. The conclusion
uses the same restricted future Lebesgue measure. The chain-rule hypotheses
remain global Lebesgue-a.e. assumptions from 27-A, then restrict to the ray. -/
theorem theorem27_operational_ignorance_iff_descent_and_action_ae_after_time
    {E U : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup U] [InnerProductSpace ℝ U]
    (T : ℝ) (N : ℝ → Set E)
    (hNclosed : ∀ t, T ≤ t → IsClosed (N t))
    (hNnonempty : ∀ t, T ≤ t → (N t).Nonempty)
    (W : ℝ × E → ℝ) (x : ℝ → E)
    (c₁ decayRate : ℝ) (hc₁ : 0 < c₁) (hdecayRate : 0 < decayRate)
    (hWlower : ∀ t, T ≤ t →
      c₁ * (Metric.infDist (x t) (N t)) ^ 2 ≤ W (t, x t))
    (hDiniDecay : ∀ t, T ≤ t →
      decayRate * W (t, x t) ≤
        -Actuator.upperRightDiniDerivative (fun s => W (s, x s)) t)
    (hforward : ∀ s t, T ≤ s → s ≤ t → x s ∈ N s → x t ∈ N t)
    (hWzero : ∀ s, T ≤ s → ∀ y, y ∈ N s → W (s, y) = 0)
    (dW : ℝ → (ℝ × E →L[ℝ] ℝ)) (gradW drift : ℝ → E)
    (u0 utr : ℝ → U) (actuator : ℝ → U →L[ℝ] E)
    (hW : ∀ᵐ t ∂futureLebesgueMeasure T,
      HasFDerivAt W (dW t) (t, x t))
    (hmodel : ∀ᵐ t ∂futureLebesgueMeasure T,
      HasDerivAt x (drift t + actuator t (u0 t)) t ∧
      (∀ z, dW t (0, z) = inner ℝ (gradW t) z) ∧
      dW t (1, 0) + inner ℝ (gradW t)
        (drift t + actuator t (utr t)) = 0)
    (hLocallyLipschitz :
      LocallyLipschitzOn (Set.Ici T) (fun s => W (s, x s)))
    (operationalIgnorance : ℝ → Prop)
    (hPZSOutside : ∀ (t : ℝ), T ≤ t →
      (operationalIgnorance t ↔ x t ∉ N t)) :
    (∀ t, T ≤ t → (operationalIgnorance t ↔
      0 < residualDescentRateAlong (fun s y => W (s, y)) x t)) ∧
    (∀ᵐ t ∂futureLebesgueMeasure T,
      operationalIgnorance t ↔
        Actuator.sankhara27Contribution (gradW t) (actuator t) (u0 t - utr t)) := by
  let descent := fun t => residualDescentRateAlong (fun s y => W (s, y)) x t
  have htargetAE : ∀ᵐ t ∂futureLebesgueMeasure T, T ≤ t := by
    filter_upwards [MeasureTheory.ae_restrict_mem measurableSet_Ici] with t ht
    exact ht
  have hzeroOnTarget : ∀ t, T ≤ t → x t ∈ N t → descent t = 0 := by
    intro t ht hmem
    have hinvariant : ∀ s, t ≤ s → x s ∈ N s := by
      intro s hts
      exact hforward t s ht hts hmem
    have hright : HasDerivWithinAt (fun s => W (s, x s)) 0 (Set.Ici t) t := by
      apply (hasDerivWithinAt_const (c := (0 : ℝ)) (s := Set.Ici t) (x := t)).congr
      · intro s hs
        exact hWzero s (ht.trans hs) (x s) (hinvariant s hs)
      · exact hWzero t ht (x t) hmem
    unfold descent residualDescentRateAlong
    rw [Actuator.upperRightDiniDerivative_eq_zero_of_hasDerivWithinAt
      (fun s => W (s, x s)) t hright]
    simp
  have hdescentOutside : ∀ t, T ≤ t → (x t ∉ N t ↔ 0 < descent t) := by
    intro t ht
    exact outside_target_iff_positive_descent (N t) (hNclosed t ht)
      (hNnonempty t ht) (fun y => W (t, y)) (x t) c₁ decayRate hc₁ hdecayRate
      (descent t) (hWlower t ht)
      (by simpa [descent, residualDescentRateAlong] using hDiniDecay t ht)
      (hzeroOnTarget t ht)
  have hDiniEq := Actuator.ae_upperRightDiniDerivative_eq_deriv_on_future
    (fun s => W (s, x s)) T hLocallyLipschitz
  have hformula := Actuator.ae_closedLoop_descent_formula_of_ode_under_measure
    W x dW gradW drift u0 utr actuator (futureLebesgueMeasure T) hW hmodel
  have hformula : ∀ᵐ t ∂futureLebesgueMeasure T,
      -(deriv (fun s => W (s, x s)) t) =
        -(inner ℝ (gradW t) (actuator t (u0 t - utr t))) := by
    exact hformula
  have hWlowerAE : ∀ᵐ t ∂futureLebesgueMeasure T,
      c₁ * (Metric.infDist (x t) (N t)) ^ 2 ≤ W (t, x t) := by
    filter_upwards [htargetAE] with t ht
    exact hWlower t ht
  have hDiniDecayAE : ∀ᵐ t ∂futureLebesgueMeasure T,
      decayRate * W (t, x t) ≤
        -Actuator.upperRightDiniDerivative (fun s => W (s, x s)) t := by
    filter_upwards [htargetAE] with t ht
    exact hDiniDecay t ht
  have hactionOutside : ∀ᵐ t ∂futureLebesgueMeasure T,
      x t ∉ N t ↔ Actuator.sankhara27Contribution
        (gradW t) (actuator t) (u0 t - utr t) := by
    filter_upwards [hWlowerAE, hDiniDecayAE, hDiniEq, hformula, htargetAE]
      with t hLower hDecay hDini hformula ht
    change x t ∉ N t ↔
      0 < -(inner ℝ (gradW t) (actuator t (u0 t - utr t)))
    constructor
    · intro houtside
      have hdist : 0 < Metric.infDist (x t) (N t) :=
        (hNclosed t ht).notMem_iff_infDist_pos (hNnonempty t ht) |>.mp houtside
      have hWpositive : 0 < W (t, x t) := by
        have hsq : 0 < (Metric.infDist (x t) (N t)) ^ 2 := sq_pos_of_pos hdist
        nlinarith [hLower]
      have hderivDecay : decayRate * W (t, x t) ≤
          -(deriv (fun s => W (s, x s)) t) := by
        simpa [hDini] using hDecay
      calc
        0 < decayRate * W (t, x t) := mul_pos hdecayRate hWpositive
        _ ≤ -(deriv (fun s => W (s, x s)) t) := hderivDecay
        _ = -(inner ℝ (gradW t) (actuator t (u0 t - utr t))) := hformula
    · intro hpositive houtside
      have htarget := hforward t t ht le_rfl houtside
      have hinvariant : ∀ s, t ≤ s → x s ∈ N s := by
        intro s hts
        exact hforward t s ht hts htarget
      have hright : HasDerivWithinAt (fun s => W (s, x s)) 0 (Set.Ici t) t := by
        apply (hasDerivWithinAt_const (c := (0 : ℝ)) (s := Set.Ici t) (x := t)).congr
        · intro s hs
          exact hWzero s (ht.trans hs) (x s) (hinvariant s hs)
        · exact hWzero t ht (x t) htarget
      have hDiniZero := Actuator.upperRightDiniDerivative_eq_zero_of_hasDerivWithinAt
        (fun s => W (s, x s)) t hright
      rw [hDini] at hDiniZero
      have hderivZero : deriv (fun s => W (s, x s)) t = 0 := by linarith
      rw [← hformula, hderivZero] at hpositive
      norm_num at hpositive
  have hPZSOutsideAE : ∀ᵐ t ∂futureLebesgueMeasure T,
      operationalIgnorance t ↔ x t ∉ N t := by
    have hPZSAt : ∀ (t : ℝ), T ≤ t →
        (operationalIgnorance t ↔ x t ∉ N t) :=
      hPZSOutside
    filter_upwards [htargetAE] with t ht
    exact hPZSAt t ht
  constructor
  · intro t ht
    exact (hPZSOutside t ht).trans (hdescentOutside t ht)
  · filter_upwards [hactionOutside, hPZSOutsideAE] with t haction hpzs
    exact hpzs.trans haction

end Tomabechi.Theorem27
