import Lake
open Lake DSL

package tomabechi_theory

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.34.1"

lean_lib Tomabechi where
  srcDir := "."
  roots := #[`Theorem1, `Theorem2, `Theorem3, `Theorem4, `Theorem1_4_HFlow, `Theorem19, `Theorem19_22, `Theorem19_Heterogeneous, `Theorem20, `Theorem21, `Theorem21_Model, `Theorem22, `Theorem23, `Theorem15,
    `Theorem15_23,
    `Theorem24_26, `Theorem24_26_27, `Theorem24_26_Model,
    `Theorem24_26_ControlledModel, `Theorem24_26_LinearFamily,
    `Theorem24_26_GainControl, `Theorem27, `Theorem16_25, `Theorem21_P13,
    `Theorem16_25_Core, `Theorem16_25_Model,
    `Tomabechi.Analysis.EntropyBalance, `Tomabechi.Information.Capacity,
    `Tomabechi.Analysis.StrongConvexity,
    `Tomabechi.Dynamics.GradientFlow,
    `Tomabechi.Dynamics.GlobalFlow,
    `Tomabechi.Dynamics.Theorem21GlobalResults,
    `Tomabechi.Theorem27.Abstract,
    `Tomabechi.Theorem27.Actuator,
    `Tomabechi.Theorem27.Connection,
    `Tomabechi.Information.MeanFieldDirectCMI,
    `Tomabechi.Information.FiniteCMI,
    `Tomabechi.Information.FiniteMeasureEntropy,
    `Tomabechi.Information.DeterministicOutput,
    `Tomabechi.Information.MeasureCMI,
    `Tomabechi.Information.MeasureCMICapacity,
    `Tomabechi.Dynamics.StageData,
    `Tomabechi.Dynamics.InvariantRegion,
    `Tomabechi.Dynamics.StageSwitching,
    `Tomabechi.Dynamics.MeanFieldReconstruction,
    `Tomabechi.Counterexamples.DecoderRegularity,
    `Tomabechi.Consistency.ConsistencyR1_CommonLattice,
    `Tomabechi.Consistency.ConsistencyR1_C1Information,
    `Tomabechi.Consistency.ConsistencyR2_PointReachability,
    `Tomabechi.Consistency.ConsistencyR3_CommonBase,
    `Tomabechi.Consistency.ConsistencyR3_Theorem4Entry,
    `Tomabechi.Consistency.ConsistencyR3_Theorem20Entry,
    `Tomabechi.Consistency.ConsistencyR1_C6Transport,
    `Tomabechi.Consistency.ConsistencyR1_C6FullIndex,
    `Tomabechi.Consistency.ConsistencyR1_C3LayerConnection,
    `Tomabechi.Consistency.ConsistencyR1_C3LiftedStage,
    `Tomabechi.Consistency.ConsistencyR1_CompletePath,
    `Tomabechi.Consistency.ConsistencyR123_SharedSignature,
    `Tomabechi.Consistency.ConsistencyR123_SharedEntropy,
    `Tomabechi.Consistency.ConsistencyR123_SharedKernelInputs,
    `Tomabechi.Consistency.ConsistencyR123_SharedTheorem4,
    `Tomabechi.Consistency.ConsistencyR123_SharedTheorem20,
    `Tomabechi.Consistency.ConsistencyR123_SharedR3Inputs,
    `Tomabechi.Consistency.ConsistencyR123_TopGeometry,
    `Tomabechi.Consistency.ConsistencyR123_SharedTopActuator,
    `Tomabechi.Consistency.ConsistencyR123_SharedTheorem27,
    `Tomabechi.Consistency.ConsistencyR123_SharedSCM,
    `Tomabechi.Consistency.ConsistencyR123_SharedExperiment,
    `Tomabechi.Consistency.ConsistencyR123_SharedStageSwitch,
    `Tomabechi.Consistency.ConsistencyR123_SharedStageInformation,
    `Tomabechi.Consistency.ConsistencyR123_SharedStageConclusion,
    `Tomabechi.Consistency.ConsistencyR123_SharedTheorem2,
    `Tomabechi.Consistency.ConsistencyR123_SharedTheorem1,
    `Tomabechi.Consistency.ConsistencyR123_SharedTheorem3,
    `Tomabechi.Consistency.ConsistencyR123_FullExperiment,
    `Tomabechi.Consistency.ConsistencyR123_FullDecoder,
    `Tomabechi.Consistency.ConsistencyR123_FullExperimentRecovery,
    `Tomabechi.Consistency.ConsistencyR123_PointDomain,
    `Tomabechi.Consistency.ConsistencyR123_Nondegenerate,
    `Tomabechi.Consistency.ConsistencyR123_Final,
    `Tomabechi.Consistency.ConsistencyR123_HConditions,
    `Tomabechi.Consistency.ConsistencyR123_SharedCapacity,
    `Tomabechi.Consistency.ConsistencyR123_Shared16Indexing,
    `Tomabechi.Consistency.ConsistencyR123_Shared16LayerTCZ,
    `Tomabechi.Consistency.ConsistencyR123_SharedBaseDomain,
    `Tomabechi.Consistency.ConsistencyR123_NativeNondegenerate,
    `Tomabechi.Consistency.ConsistencyR123_ReadingClosures,
    `Tomabechi.Consistency.ConsistencyR123_FinalV2,
    `Tomabechi.Consistency.ConsistencyR123_ModelExamples,
    `Tomabechi.Consistency.ConsistencyR123_BaseAsStageBackground,
    `Tomabechi.Consistency.ConsistencyR123_TopCompleteState,
    `Tomabechi.Consistency.ConsistencyR123_NormUnificationConclusions,
    `Tomabechi.Consistency.ConsistencyR123_Theorem4Ranges,
    `Tomabechi.Consistency.ConsistencyR123_Shared16Premises,
    `Tomabechi.Consistency.ConsistencyR123_SubjectIdentity,
    `Tomabechi.Consistency.ConsistencyR123_NoClockCoordinate,
    `Tomabechi.Consistency.ConsistencyR123_BorelStructure,
    `Tomabechi.Consistency.ConsistencyR123_GenealogyMortality,
    `Tomabechi.Consistency.ConsistencyR123_Shared16OnePoint,
    `Tomabechi.Consistency.ConsistencyR123_Theorem21V0Instance,
    `Tomabechi.Consistency.ConsistencyR123_MortalityOnN,
    `Tomabechi.Consistency.ConsistencyR123_CanonicalTCZ,
    `Tomabechi.Consistency.ConsistencyR123_CommonDomainX,
    `Tomabechi.Consistency.ConsistencyR123_FixedCapacity,
    `Tomabechi.Consistency.ConsistencyR123_DomainTheorems,
    `Tomabechi.Consistency.ConsistencyR123_FinalGate,
    `Tomabechi.Consistency.ConsistencyR123_Theorem3Domain,
    `Tomabechi.Consistency.ConsistencyR123_LayerControl,
    `Tomabechi.Consistency.ConsistencyR123_FullSelf,
    `Tomabechi.Consistency.ConsistencyR123_CurrentPremises,
    `Tomabechi.Consistency.ConsistencyR123_PolicyCapacity,
    `Tomabechi.Consistency.ConsistencyR123_FinalV13,
    `Tomabechi.Consistency.ConsistencyR123_FinalV14,
    `Tomabechi.Consistency.ConsistencyR123_SelfProcessOnePoint,
    `Tomabechi.Consistency.ConsistencyR123_FinalV6,
    `Theorem19_Counterexample, `Theorem22_InvariantRegion,
    `Theorem22_InvariantRegion_P13,
    `Theorem23_InvariantRegion, `Theorem22_InvariantRegion_Model,
    `Econlib.Math.Combinatorics.FreudenthalTriangulation,
    `Econlib.Math.Combinatorics.CubicalSperner,
    `Econlib.Math.Topology.ConvexHomeomorph, `Econlib.Math.Topology.Brouwer,
    `Econlib.Math.Topology.Kakutani,
    `Econlib.Math.Topology.FanGlicksberg,
    `Tomabechi.Examples.Theorem23B_QuadraticStages,
    `Tomabechi.Examples.Theorem22_GaussianStages,
    `Tomabechi.Examples.Theorem26_ValueZeroSet, `Tomabechi.Examples.Theorem26_RingModel, `Tomabechi.Examples.Theorem22_HStage,
    `Tomabechi.Examples.Theorem25_NoSelf, `Tomabechi.Examples.Theorem27_AvijjaSankhara, `Tomabechi.Examples.Theorem27_Operational, `Tomabechi.Examples.Theorem26_27_ControlClasses,
    `Tomabechi.Examples.Theorem16_Identity, `Tomabechi.Examples.Theorem20_SymbolicPresence, `Tomabechi.Examples.Theorem15_EntropyExchange, `Tomabechi.Examples.Theorem23_Impermanence, `Tomabechi.Examples.Gaussian, `Tomabechi.Examples.Theorem22_LubStaircase, `Tomabechi.Examples.Theorem4_PresenceWeight, `Tomabechi.Examples.Theorem24_Tracking, `Tomabechi.Examples.Theorem21_GaussianValley, `Tomabechi.Examples.Theorem19_FreeWillCapacity, `Tomabechi.Examples.Theorem16_Tower, `Tomabechi.Examples.Theorem16_TowerLayers, `Tomabechi.Examples.Theorem1_DoubleWell, `Tomabechi.Examples.Theorem3_LubConsensus, `Tomabechi.Examples.Theorem2_SharedTCZ, `Tomabechi.Examples.Theorem2_SubgradientFlow, `Tomabechi.Consistency.ConsistencyC1_HFlow, `Tomabechi.Consistency.ConsistencyC1_Consensus, `Tomabechi.Consistency.ConsistencyC1_Theorem4, `Tomabechi.Consistency.ConsistencyC1_O24, `Tomabechi.Consistency.ConsistencyC1_ConsensusControl, `Tomabechi.Consistency.ConsistencyC1_Theorem3Bridge, `Tomabechi.Consistency.ConsistencyC1_CommonModel, `Tomabechi.Consistency.ConsistencyC1_DataIdentifications, `Tomabechi.Consistency.ConsistencyC2_EntropyBalance, `Tomabechi.Examples.Theorem15_A6Failure,
    `Tomabechi.Consistency.ConsistencyC3_StagePresentation,
    `Tomabechi.Consistency.ConsistencyC4_Theorem16_25,
    `Tomabechi.Consistency.ConsistencyC5_Theorem24_27,
    `Tomabechi.Consistency.ConsistencyC6_Integration,
    `Tomabechi.Consistency.ConsistencyC6_C1Connections,
    `Tomabechi.Consistency.ConsistencyC6_ControlCore,
    `Tomabechi.Consistency.ConsistencyC6_CommonLayerData,
    `Tomabechi.Consistency.ConsistencyC6_FiniteDataAdapter,
    `Tomabechi.Consistency.ConsistencyC6_CenteredContexts,
    `Tomabechi.Consistency.ConsistencyC6_TypedSelfProcess,
    `Tomabechi.Consistency.ConsistencyC6_FullLayerSCM,
    `Tomabechi.Consistency.ConsistencyR1_C6CommonConceptSCM,
    `Tomabechi.Consistency.ConsistencyC6_SharedExperiment,
    `Tomabechi.Consistency.ConsistencyC6_TopActuator,
    `Tomabechi.Consistency.ConsistencyC6_ModelSignature,
    `Tomabechi.Consistency.ConsistencyR1_C6Information,
    `Tomabechi.Consistency.ConsistencyC6_Nondegenerate,
    `Tomabechi.Consistency.ConsistencyC6_EntropyInputs,
    `Tomabechi.Consistency.ConsistencyC6_ActuatorInputs,
    `Tomabechi.Consistency.ConsistencyC6_SignatureSelfProcess,
    `Tomabechi.Consistency.ConsistencyC6_OriginalLayerInputs,
    `Tomabechi.Consistency.ConsistencyC6_Acceptance,
    `Tomabechi.Consistency.ConsistencyC6_TopUniqueness,
    `Tomabechi.Consistency.ConsistencyC6_FiniteUniqueness,
    `Tomabechi.Consistency.ConsistencyC6_EntryAdapters,
    `theorem1_example, `Theorem1_Model]
