import Tomabechi.Information.MeasureCMI
import Tomabechi.Information.MeasureCMICapacity
import Tomabechi.Counterexamples.DecoderRegularity

/-! # 互換入口

定理19/22の一般測度CMI接続は `Tomabechi.Information.MeasureCMI`、
出力可測性の反例証人は `Tomabechi.Counterexamples.DecoderRegularity` に配置した。
この旧モジュール名と既存の公理監査コマンドを維持する。
-/

#print axioms Tomabechi.Theorem19_22.posteriorGoalKernel_disintegrates
#print axioms Tomabechi.Theorem19_22.finiteKernelGoalEntropyAt_integrable
#print axioms Tomabechi.Theorem19_22.finiteKernelGoalSurprisal_integrable
#print axioms Tomabechi.Theorem19_22.finiteKernelGoalSurprisal_integral_compProd
#print axioms Tomabechi.Theorem19_22.finiteKernel_log_rnDeriv_eq_surprisal_sub
#print axioms Tomabechi.Theorem19_22.finiteKernel_log_rnDeriv_le_surprisal
#print axioms Tomabechi.Theorem19_22.finiteKernelCompProd_llr_eq_surprisal_sub
#print axioms Tomabechi.Theorem19_22.finiteKernelCompProd_kl_eq_cross_entropy_sub
#print axioms Tomabechi.Theorem19_22.actionGoalJoint_kl_eq
#print axioms Tomabechi.Theorem19_22.referenceActionGoalJoint_eq
#print axioms Tomabechi.Theorem19_22.posteriorGoalEntropy_nonneg
#print axioms Tomabechi.Theorem19_22.posteriorGoalEntropy_integrable
#print axioms Tomabechi.Theorem19_22.posteriorGoalEntropy_le_card
#print axioms Tomabechi.Theorem19_22.cmiLawOfJoint_joint
#print axioms Tomabechi.Theorem19_22.cmiLawOfJoint_reference_eq
#print axioms Tomabechi.Theorem19_22.finite_measure_cmi_eq_entropy_sub_posterior
#print axioms Tomabechi.Theorem19_22.finite_measure_cmi_le_inputGoalEntropy
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_eq_zero_of_inputGoalEntropy_zero
#print axioms Tomabechi.Theorem19_22.posteriorGoalKernel_eq_deterministic_of_recovery
#print axioms Tomabechi.Theorem19_22.posteriorGoalEntropy_eq_zero_of_recovery
#print axioms Tomabechi.Theorem19_22.finite_measure_cmi_eq_inputGoalEntropy_of_recovery
#print axioms Tomabechi.Theorem19_22.finiteGoalDecoder_measurable
#print axioms Tomabechi.Theorem19_22.finite_measure_cmi_eq_inputGoalEntropy_of_injective_deterministic_action
#print axioms Tomabechi.Theorem19_22.finite_measure_cmi_eq_inputGoalEntropy_of_injective_deterministic_joint
#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.no_measurable_leftInverse
#print axioms Tomabechi.Theorem19_22.dependentMeasureCMICapacity_eq_pooledLayerCapacity
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_nondecreasing
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_nondecreasing_of_pair_preserving
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_monotone_along_lub_stages
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_nonnegative
#print axioms Tomabechi.Theorem19_22.finite_measure_cmi_score_eq_zero_of_joint_eq_reference
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_eq_zero_of_independence
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_capacity_eq_zero_of_zero_entropy_bound
#print axioms Tomabechi.Theorem19_22.dependent_measure_cmi_endpoint_normalization_values

#print axioms Tomabechi.Theorem19_22.directCMIReference_isProbabilityMeasure
#print axioms Tomabechi.Theorem19_22.directActionGoalJoint_disintegrates

#print axioms Tomabechi.Theorem19_22.directPriorGoalKernel_disintegrates
#print axioms Tomabechi.Theorem19_22.directPriorGoalKernel_markov
#print axioms Tomabechi.Theorem19_22.directActionGoalJoint_fst

#print axioms Tomabechi.Theorem19_22.directPriorSurprisal_integrable
#print axioms Tomabechi.Theorem19_22.directPriorSurprisal_integral

#print axioms Tomabechi.Theorem19_22.directCMI_eq_entropy_sub_posterior

#print axioms Tomabechi.Theorem19_22.directCMI_le_inputGoalEntropy_of_finite

#print axioms Tomabechi.Theorem19_22.heterogeneous_directCMI_capacity_eq_zero

#print axioms Tomabechi.Theorem19_22.directPriorGoalKernel_eq_existing

#print axioms Tomabechi.Theorem19_22.directCMIReference_eq_existing

#print axioms Tomabechi.Theorem19_22.directCMI_kl_eq_existing

#print axioms Tomabechi.Theorem19_22.directPosteriorGoalKernel_eq_deterministic_of_recovery
#print axioms Tomabechi.Theorem19_22.directPriorGoalKernel_mass_pos_ae
#print axioms Tomabechi.Theorem19_22.directCMI_absolutelyContinuous_of_recovery
#print axioms Tomabechi.Theorem19_22.directCMI_eq_inputGoalEntropy_of_recovery_of_support
#print axioms Tomabechi.Theorem19_22.directCMI_eq_inputGoalEntropy_of_recovery

#print axioms Tomabechi.Theorem19_22.directCMI_eq_inputGoalEntropy_of_injective_deterministic_action
#print axioms Tomabechi.Theorem19_22.directCMI_eq_inputGoalEntropy_of_injective_deterministic_action_of_support
#print axioms Tomabechi.Theorem19_22.directCMI_eq_inputGoalEntropy_of_injective_deterministic_joint

#print axioms Tomabechi.Theorem19_22.finiteGoalDecoder_measurable_of_action_graphs

#print axioms Tomabechi.Theorem19_22.directCMI_eq_inputGoalEntropy_of_action_graphs

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.not_all_action_graphs_measurable

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.dirac_goal_encode_eq
#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.klDiv_dirac_encode_eq_zero

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryEncodedJoint_eq_constant
#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryEncodedJoint_kl_constant_eq_zero

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryConstantJoint_eq_product
#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryGoalEntropy_pos

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryEncodedJoint_mutualInformation_eq_zero
#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryEncodedJoint_information_lt_goalEntropy

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryContextLaw_cmi_eq_zero

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryContextLaw_inputEntropy_eq_log_two

#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryContextLaw_generated_by_encode
#print axioms Tomabechi.Theorem19_22.DecoderRegularityWitness.binaryContextLaw_cmi_lt_inputEntropy

#print axioms Tomabechi.Theorem19_22.directCMI_ne_top_of_ac
